app_addfriend/urls.py
from django.conf.urls import url, include
from .views import index, add_friend

urlpatterns = [
    url(r'^$',index, name="friends"),
    url(r'^add_friend/$',add_friend, name="add_friend"),
]

app_profile/urls.py
from django.conf.urls import url, include
from .views import index

urlpatterns = [
    url(r'^$',index, name="profile"),
]

app_stats/urls.py
from django.conf.urls import url, include
from .views import index

urlpatterns = [
    url(r'^$',index, name="stats"),
]

app_status/urls.py
from django.conf.urls import url, include
from .views import index, update_status, comment_page, insert_comment

urlpatterns = [
    url(r'^$',index, name="status"),
    url(r'^update_status/$', update_status, name='update_status'),
    url(r'^comment_page/$', comment_page, name='comment_page'),
    url(r'^insert_comment/$', insert_comment, name='insert_comment')
]

t1ka/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import app_status.urls as app_status
import app_profile.urls as app_profile
import app_addfriend.urls as app_addfriend
import app_stats.urls as app_stats
from app_status.views import index as index_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include(app_status, namespace="app_status")),
    url(r'^profile/', include(app_profile, namespace="app_profile")),
    url(r'^friends/', include(app_addfriend, namespace="app_addfriend")),
    url(r'^stats/', include(app_stats, namespace="app_stats")),
    url(r'^$', index_status, name='index')
]

app_addfriend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=30)
    url = models.URLField()
    date = models.DateTimeField(auto_now_add=True)

app_profile/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    MALE = 1
    FEMALE = 2
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
    name = models.CharField(max_length=30, null='True')
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null='True')
    birth_date = models.DateField(null='True')
    email = models.EmailField(null='True')
    expertise = models.TextField(null='True')
    description = models.TextField(null='True')

app_stats/models.py
from django.db import models

# Create your models here.

app_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    content = models.CharField(max_length=280)
    date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    name = models.CharField(max_length=40)
    content = models.CharField(max_length=280)
    date = models.DateTimeField(auto_now_add=True)
    status_id = models.IntegerField()

app_addfriend/forms.py
from django import forms

class Addfriend_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Name', required=True, max_length=30, widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(label='URL',required=True,widget=forms.URLInput(attrs=attrs))

app_status/forms.py
from django import forms

class UpdateStatusForm(forms.Form):
    attrs = {
        'class': 'form-control',
        'placeholder': 'Apa yang sedang Anda pikirkan?'
    }

    content = forms.CharField(label='Update Status', required=True, max_length=280, widget=forms.TextInput(attrs=attrs))

class InsertCommentForm(forms.Form):
    attrs_name = {
        'class': 'form-control',
        'placeholder': 'Siapa namamu?'
    }

    attrs_content = {
        'class': 'form-control',
        'placeholder': 'Apa tanggapanmu tentang Status tadi?'
    }

    name = forms.CharField(label='Nama', required=True, max_length=40, widget=forms.TextInput(attrs=attrs_name))
    content = forms.CharField(label='Tulis komentar Anda di sini', required=True, max_length=280, widget=forms.TextInput(attrs=attrs_content))
    #status_id = forms.CharField(widget=forms.HiddenInput())

app_addfriend/views.py
from django.shortcuts import render, redirect
from .forms import Addfriend_Form
from .models import Friend
# Create your views here.
response = {}
def index(request):
    html = 'addfriend.html'
    response['addfriend'] = Addfriend_Form
    response['friend'] = Friend.objects.all().order_by('date')
    return render(request,html,response)

def add_friend(request):
    form = Addfriend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friend(name=response['name'], url=response['url'])
        friend.save()
        return redirect ('/friends/')

app_profile/views.py
from django.shortcuts import render
from .models import Profile
# Create your views here.

def index(request):
    if Profile.objects.all().count()==0:
        Profile.objects.create(
            name="Tika Tikung",
            gender=2,
            birth_date="1997-5-26",
            email="adadeh@mail.com",
            expertise="Makan, Jalan-jalan",
            description="Nothing",
            )

    profil = Profile.objects.get(id=1)

    if profil.gender==1:
        profil.gender='Male'
    else:
        profil.gender='Female'

    response = {
    'name':profil.name,
    'gender':profil.gender,
    'birthdate':profil.birth_date,
    'email':profil.email,
    'expertise':[data.strip() for data in profil.expertise.split(',')],
    'description':profil.description,
    }
    html = 'profile.html'
    return render(request, html, response)

app_stats/views.py
from django.shortcuts import render
from app_profile.models import Profile
from app_addfriend.models import Friend
from app_status.models import Status
# Create your views here.

def index(request):
    profil = Profile.objects.get(id=1)
    response = {
    'name': profil.name,
    'latest_post': Status.objects.latest('id'),
    'feed': Status.objects.all().count(),
    'friends': Friend.objects.all().count()
    }
    html = 'stats.html'
    return render(request, html, response)

app_status/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import UpdateStatusForm, InsertCommentForm
from .models import Status, Comment
from app_profile.models import Profile

# Create your views here.
def index(request):
    response = {}
    html = 'status.html'
    response['update_status'] = UpdateStatusForm
    response['all_status'] = Status.objects.all().order_by('-date')
    response['all_comment'] = Comment.objects.all().order_by('-date')
    
    profil = Profile.objects.get(id=1)
    response['name'] = profil.name
    return render(request,html,response)

def update_status(request):
    response = {}
    form = UpdateStatusForm(request.POST or None, auto_id=False)
    if(request.method == 'POST' and form.is_valid()):
        response['content'] = request.POST['content']
        status = Status(content=response['content'])
        status.save()
        return redirect ('/status/')

def comment_page(request):
    response = {}
    html = 'comment.html'
    response['status_id'] = request.POST.get('status_id', None)
    response['comment_form'] = InsertCommentForm
    return render(request,html,response)

def insert_comment(request):
    response = {}
    form = InsertCommentForm(request.POST or None, auto_id=False)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['content'] = request.POST['content']
        response['status_id'] = request.POST['status_id']

        comment = Comment(name=response['name'] , content=response['content'], status_id=response['status_id'])
        comment.save()
        return HttpResponseRedirect ('/status/')

app_addfriend/templates/addfriend.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container h-100" style="padding-top:30px;padding-bottom:60px">
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Add Friend</li>
  </ol>
</nav>
<form id="form" method="POST" action="{% url 'app_addfriend:add_friend' %}">
  {% csrf_token %}
  {{ addfriend.as_p }}
  <button type="submit" class="btn btn-dark float-right">Add Friend</button>
</form>
<nav aria-label="breadcrumb " style="padding-top:100px">
<ol class="breadcrumb">
  <li class="breadcrumb-item active" aria-current="page">List Friends</li>
</ol>
</nav>
<div class="table-responsive">
<table class="table">
  <thead>
      <tr>
        <th>Name</th>
        <th>URL</th>
        <th>Added Time</th>
      </tr>
        <tbody>
            {% for i in friend %}
            <tr>
                <td> {{i.name}} </td>
                <td> <a href="{{i.url}}">{{i.url}}</a></td>
                <td> {{i.date}} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}

app_profile/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container h-100" style="padding-top:30px;padding-bottom:60px">
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Profile</li>
  </ol>
</nav>
  <div class="row justify-content-center" style="margin-top:40px">
    <div class="col-12 text-center">
      <img src="{% static 'image/tes1.jpeg' %}" class="rounded-circle" width="200" height="200"/>
    </div>
  </div>
  <div class="row" style="margin-top:10px; margin-bottom:30px">
    <div class="col-12 text-center">
      <h2>{{name}}</h2>
    </div>
  </div>
  <div class="row justify-content-center"  style="margin-top:10px; margin-bottom:10px">
    <div class="col-3">
      <span class="lead">Gender</lead>
    </div>
    <div class="col-6">
      {{gender}}
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top:10px; margin-bottom:10px">
    <div class="col-3">
      <span class="lead">Birthdate</lead>
    </div>
    <div class="col-6">
      {{birthdate}}
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top:10px; margin-bottom:10px">
    <div class="col-3">
      <span class="lead">Email</lead>
    </div>
    <div class="col-6">
      {{email}}
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top:10px; margin-bottom:10px">
    <div class="col-3">
      <span class="lead">Expertises</lead>
    </div>
    <div class="col-6">
      {% for ex in expertise %}
      <span class="badge badge-pill badge-dark lead">{{ex}}</span>
      {% endfor %}
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top:10px; margin-bottom:10px">
    <div class="col-3">
      <span class="lead">Description</lead>
    </div>
    <div class="col-6">
      {{description}}
    </div>
  </div>
</div>
{% endblock %}

app_stats/templates/stats.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container h-100" style="padding-top:30px;padding-bottom:60px">
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Stats</li>
  </ol>
</nav>

  <div class="row" style="margin-top:40px">
    <div class="col-md-2 text-center">
      <img src="{% static 'image/tes1.jpeg' %}" class="rounded-circle" width="100" height="100"/>
    </div>
    <div class="col-md-10" style="vertical-align: middle;">
      <h2>{{name}}</h2>
      <p class="lead">
      Friends : {{friends}}
      <br>
      Feed : {{feed}}</p>
    </div>
  </div>
  <div class="row" style="margin-top:40px; margin-left:15px">
    <span class="lead">Latest Post</span>
  </div>
  <div class="row" style="margin-top:10px; margin-left:15px">
    <img src="{% static 'image/tes1.jpeg' %}" class="rounded-circle" width="50" height="50"/>
  </div>
  <div class="row" style="margin-top:10px; margin-left:15px">
    <h6>{{name}}</h6>
  </div>
  <div class="row" style="margin-top:5px; margin-left:15px">
      <p class="mb-0">{{latest_post.content}}</p>
  </div>
  <div class="row" style="margin-top:5px; margin-left:15px">
  {{latest_post.date}}
  </div>
</div>
{% endblock %}

app_status/templates/comment.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container h-100" style="padding-top:30px;padding-bottom:60px">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Komentar</li>
    </ol>
  </nav>
  <p>Status id: {{ status_id }}</p>
  <form id="form" method="POST" action="{% url 'app_status:insert_comment' %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="hidden" value="{{ status_id }}" name="status_id" />
    <button type="submit" class="btn btn-dark float-right">Submit</button>
  </form>
</div>
{% endblock %}

app_status/templates/status.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container h-100" style="padding-top:30px;padding-bottom:60px">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Lini Masa</li>
    </ol>
  </nav>
  <form id="form" method="POST" action="{% url 'app_status:update_status' %}">
    {% csrf_token %}
    {{ update_status.as_p }}
    <button type="submit" class="btn btn-dark float-right">Post</button>
  </form>
</div>

<div class="container h-100" style="padding-top:30px;padding-bottom:60px">
  {% for status in all_status %}
    <div class="card" style="">
      <div class="card-body">
        <img src="{% static 'image/tes1.jpeg' %}" class="rounded-circle" width="50" height="50" border="2px" style="vertical-align: middle;"/>
        <h5 class="card-title" style="vertical-align: middle; display:inline-block;"><b>&ensp;{{ name }}</b></h5></br></br>
        <p class="card-text">{{ status.content }}</p>
        <form action="{% url 'app_status:comment_page' %}" method="post">
          {% csrf_token %}
          <input type="hidden" value="{{ status.id }}" name="status_id" />
          <input type="submit" name="insert_comment" value="Comment" class="btn btn-primary float-right">
        </form>
      </div>
      <div class="card-footer">
        <small class="text-muted">{{ status.date }}</small></br>
        <small class="text-muted">Status id: {{ status.id }}</small>
      </div>
    </div>

    {% for comment in all_comment %}
      {% ifequal status.id comment.status_id %}
        <div class="card w-75" style="margin-left:auto; margin-right:0;">
          <div class="card-body">
            <h5 class="card-title"><b>{{ comment.name }}</b></h5>
            <p class="card-text">{{ comment.content }}</p>
          </div>
          <div class="card-footer">
            <small class="text-muted">{{ comment.date }}</small></br>
            <small class="text-muted">Status id: {{ status.id }}</small>
          </div>
        </div> 
      {% endifequal %}
    {% endfor %}

    </br></br>
  {% endfor %}
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>ThinkedIn</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/footer.css" %}" />
  </head>
  <body>
    <header>
        {% include "header.html" %}
    </header>

      {% block content %}
      {% endblock %}

    <footer class="footer">
        {% include "footer.html" %}
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
<div class="text-center bg-dark">
  <span class="text-muted">ThinkedIn &copy; 2018</span>
</div>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark container-fluid sticky-top">
  <div class="container">
<a class="navbar-brand" href="{% url 'app_status:status' %}">ThinkedIn</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
{% with url_name=request.resolver_match.view_name %}
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav ml-auto">
<li class="nav-item">
  <a class="nav-link {% if url_name == 'app_status:status' %}active{% endif %}" href="{% url 'app_status:status' %}">Status</a>
</li>
<li class="nav-item">
  <a class="nav-link {% if url_name == 'app_profile:profile' %}active{% endif %}" href="{% url 'app_profile:profile' %}">Profile</a>
</li>
<li class="nav-item">
  <a class="nav-link {% if url_name == 'app_addfriend:friends' %}active{% endif %}" href="{% url 'app_addfriend:friends' %}">Friends</a>
</li>
<li class="nav-item">
  <a class="nav-link {% if url_name == 'app_stats:stats' %}active{% endif %}" href="{% url 'app_stats:stats' %}">Stats</a>
</li>
</ul>
</div>
{% endwith %}
</div>
</nav>